[package]
name = "occulus-discord-bot"
version = "0.3.0"
edition = "2018"

[dependencies]
futures-util = "0.3"
jsonrpc-core = "18.0"
jsonrpc-derive = "18.0"
jsonrpc-tcp-server = "18.0"
log = "0.4.14"
r2d2 = "0.8.9"
r2d2_sqlite = "0.18.0"
rand = "0.8.4"
rust-embed = "6.0.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_repr = "0.1"
serenity = { version = "0.10", features = ["collector"] }
tokio = { version = "1.0", features = ["full"] }
tracing = "0.1.26"
tracing-log = "0.1.2"
tracing-subscriber = "0.2"
